// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKnpZ7iRz7JWv00NsZbWFtQzIRYdUB-Ss',
    appId: '1:644497551786:web:9b02d41c8277f1096a7bd3',
    messagingSenderId: '644497551786',
    projectId: 'flutter-practice-64aaa',
    authDomain: 'flutter-practice-64aaa.firebaseapp.com',
    storageBucket: 'flutter-practice-64aaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4F-OxqbFhhPWpqchOm0mKErLXgisLBLM',
    appId: '1:644497551786:android:00631313f79933636a7bd3',
    messagingSenderId: '644497551786',
    projectId: 'flutter-practice-64aaa',
    storageBucket: 'flutter-practice-64aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhPdRooHPFC89cZcN3N_85XQhbjqaz2sI',
    appId: '1:644497551786:ios:c5120a05bc865e336a7bd3',
    messagingSenderId: '644497551786',
    projectId: 'flutter-practice-64aaa',
    storageBucket: 'flutter-practice-64aaa.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhPdRooHPFC89cZcN3N_85XQhbjqaz2sI',
    appId: '1:644497551786:ios:27d758cd6a53e4616a7bd3',
    messagingSenderId: '644497551786',
    projectId: 'flutter-practice-64aaa',
    storageBucket: 'flutter-practice-64aaa.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
